import { useEffect, useState } from "react";
import {
  documentDirectory,
  getInfoAsync,
  deleteAsync,
  makeDirectoryAsync,
  copyAsync,
} from "expo-file-system/legacy";
import { Platform } from "react-native";
import { toErrorMessage } from "@couch-kit/core";

export interface AssetManifest {
  files: string[];
}

export interface ExtractAssetsResult {
  /** The filesystem path to the extracted www directory, or undefined if not ready */
  staticDir: string | undefined;
  /** Whether extraction is in progress */
  loading: boolean;
  /** Error message if extraction failed */
  error: string | null;
}

/**
 * Extracts bundled web assets from the APK to the filesystem so the native
 * HTTP server can serve them.
 *
 * On Android, assets live inside the APK and cannot be served directly by
 * a native HTTP server. This hook copies each file listed in the manifest
 * from `asset:///www/<file>` to `${documentDirectory}www/<file>`.
 *
 * On iOS, assets are accessible from the bundle directory, so extraction
 * is skipped and `staticDir` is returned as `undefined` (the server falls
 * back to the bundle path).
 *
 * @param manifest - The asset manifest generated by `couch-kit bundle`.
 *                   Contains a `files` array listing all relative paths.
 */
export function useExtractAssets(manifest: AssetManifest): ExtractAssetsResult {
  const [staticDir, setStaticDir] = useState<string | undefined>(undefined);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // iOS: skip extraction, server uses bundle path fallback
    if (Platform.OS !== "android") {
      setLoading(false);
      return;
    }

    let cancelled = false;

    const extractAssets = async () => {
      try {
        if (!documentDirectory) {
          throw new Error("Document directory is not available");
        }

        const targetDir = `${documentDirectory}www/`;

        // Clean previous extraction to ensure fresh assets after app updates
        const dirInfo = await getInfoAsync(targetDir);
        if (dirInfo.exists) {
          await deleteAsync(targetDir, { idempotent: true });
        }

        // Create the root target directory
        await makeDirectoryAsync(targetDir, { intermediates: true });

        // Copy each file from APK assets to filesystem
        for (const file of manifest.files) {
          if (cancelled) return;

          const sourceUri = `asset:///www/${file}`;
          const destUri = `${targetDir}${file}`;

          // Ensure subdirectory exists (e.g., "assets/" in "assets/index.js")
          const lastSlash = file.lastIndexOf("/");
          if (lastSlash > 0) {
            const subDir = `${targetDir}${file.substring(0, lastSlash)}`;
            await makeDirectoryAsync(subDir, { intermediates: true });
          }

          await copyAsync({ from: sourceUri, to: destUri });
        }

        if (cancelled) return;

        // Strip file:// prefix for the native HTTP server
        const rawPath = targetDir.replace(/^file:\/\//, "");
        setStaticDir(rawPath);
      } catch (e) {
        if (!cancelled) {
          const message = toErrorMessage(e);
          console.warn("[CouchKit] Asset extraction failed:", message);
          setError(message);
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    };

    extractAssets();

    return () => {
      cancelled = true;
    };
  }, [manifest]);

  return { staticDir, loading, error };
}
